---

- name: Copy the RPM Nginx file
  copy: src=nginx-release-centos-7-0.el7.ngx.noarch.rpm dest=/tmp/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: Install nginx repo
  shell: rpm -Uvh /tmp/nginx-release-centos-7-0.el7.ngx.noarch.rpm || /bin/true

- name: Install nginx
  yum: name=nginx state=present

- name: Create
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
